### ISSUE TITLE
Error 500 encountered on some job detail page

### ISSUE THREAD

**Issue by mikaoelitiana** [patcito/nextjob#2]
When I open some job details page (not all), I get an Error 500. 

<img width="1909" alt="capture d ecran 2019-02-14 a 14 54 35" src="https://user-images.githubusercontent.com/674667/52791156-99686b00-3068-11e9-8ccd-1acd865da8d2.png">

It may be linked to the `null` value displayed on the job listing page : 

<img width="1301" alt="capture d ecran 2019-02-14 a 14 56 21" src="https://user-images.githubusercontent.com/674667/52791246-c87edc80-3068-11e9-98e8-9e33f959874f.png">

**Comment by patcito** [comment]
Fixed.
